ALTER TABLE indicator ALTER COLUMN value TYPE NUMERIC(18,4) USING value::NUMERIC(18,4);

ALTER TABLE indicator
  ADD IF NOT EXISTS value_ma NUMERIC(18,4) NOT NULL DEFAULT 0;

ALTER TABLE indicator
  ADD IF NOT EXISTS value_ma_trend NUMERIC(18,4) NOT NULL DEFAULT 0;

ALTER TABLE indicator
  ADD IF NOT EXISTS value_ma_trend_x2 NUMERIC(18,4) NOT NULL DEFAULT 0;
